server:
  port: 8180
  servlet:
    context-path: /api
  tomcat:
    max-http-form-post-size: 100MB
    max-swallow-size: 100MB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/<YOUR DB NAME>?useSSL=false
    username: <YOUR DB USERNAME>
    password: <YOUR DB PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
logging:
  file:
    path: <PATH TO LOG FILE>
  level:
    root: ERROR

app:
  executor:
    corePoolSize: 2
    maximumPoolSize: 2
    blockingQueueCapacity: 50
  image-magick:
    command: /usr/bin/convert
    execution-time-limit: 120
  directory:
    tessdata: <PATH TO TESSDATA>
    uploads: <PATH TO FOLDER UPLOADS>